' <auto-generated />
Imports eShopDashboard.Infrastructure.Data.Catalog
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.EntityFrameworkCore.Storage
Imports Microsoft.EntityFrameworkCore.Storage.Internal
Imports System

Namespace eShopDashboard.Infrastructure.Migrations.Catalog
	<DbContext(GetType(CatalogContext))>
	Partial Friend Class CatalogContextModelSnapshot
		Inherits ModelSnapshot

		Protected Overrides Sub BuildModel(modelBuilder As ModelBuilder)
#Disable Warning BC612, BC618
			modelBuilder.HasAnnotation("ProductVersion", "2.0.2-rtm-10011").HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

			modelBuilder.Entity("eShopDashboard.EntityModels.Catalog.CatalogItem", Sub(b)
					b.Property(Of Integer)("Id")

					b.Property(Of Integer)("AvailableStock")

					b.Property(Of Integer)("CatalogBrandId")

					b.Property(Of Integer)("CatalogTypeId")

					b.Property(Of String)("Description")

					b.Property(Of Integer)("MaxStockThreshold")

					b.Property(Of String)("Name").IsRequired().HasMaxLength(50)

					b.Property(Of Boolean)("OnReorder")

					b.Property(Of String)("PictureFileName")

					b.Property(Of String)("PictureUri")

					b.Property(Of Decimal)("Price")

					b.Property(Of Integer)("RestockThreshold")

					b.Property(Of String)("TagsJson").HasMaxLength(4000)

					b.HasKey("Id")

					b.ToTable("CatalogItems","Catalog")
			End Sub)
#Enable Warning BC612, BC618
		End Sub
	End Class
End Namespace
