' <auto-generated />
Imports eShopDashboard.Infrastructure.Data.Ordering
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.EntityFrameworkCore.Storage
Imports Microsoft.EntityFrameworkCore.Storage.Internal
Imports System

Namespace eShopDashboard.Infrastructure.Migrations.Ordering
	<DbContext(GetType(OrderingContext))>
	<Migration("20180430095022_AddDescriptionsMigration_OrderingContext")>
	Partial Public Class AddDescriptionsMigration_OrderingContext
		Protected Overrides Sub BuildTargetModel(modelBuilder As ModelBuilder)
#Disable Warning BC612, BC618
			modelBuilder.HasAnnotation("ProductVersion", "2.0.2-rtm-10011").HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)

			modelBuilder.Entity("eShopDashboard.EntityModels.Ordering.Order", Sub(b)
					b.Property(Of Integer)("Id")

					b.Property(Of String)("Address_Country").HasMaxLength(100)

					b.Property(Of String)("Description").HasMaxLength(1000)

					b.Property(Of DateTime)("OrderDate")

					b.HasKey("Id")

					b.ToTable("Orders","Ordering")
			End Sub)

			modelBuilder.Entity("eShopDashboard.EntityModels.Ordering.OrderItem", Sub(b)
					b.Property(Of Integer)("Id")

					b.Property(Of Integer)("OrderId")

					b.Property(Of Integer)("ProductId")

					b.Property(Of String)("ProductName").HasMaxLength(100)

					b.Property(Of Decimal)("UnitPrice")

					b.Property(Of Integer)("Units")

					b.HasKey("Id")

					b.HasIndex("OrderId")

					b.ToTable("OrderItems","Ordering")
			End Sub)

			modelBuilder.Entity("eShopDashboard.EntityModels.Ordering.OrderItem", Sub(b)
					b.HasOne("eShopDashboard.EntityModels.Ordering.Order", "Order").WithMany().HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade)
			End Sub)
#Enable Warning BC612, BC618
		End Sub
	End Class
End Namespace
